apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels:
    app: wordpress-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:  
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-rs
  labels:
    app: wordpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress-deployment
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress-deployment
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.0-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-wp
        - name: WORDPRESS_DB_PASSWORD
          value: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-deployment
  name: wordpress-service
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-deployment
  sessionAffinity: None
  type: LoadBalance
